export const UserConstants = Object.freeze({
    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    USER_LOGOUT: 'USER_LOGOUT',
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAIL: 'USER_REGISTER_FAIL'
})

export const PlatformConstants = Object.freeze({
    PLATFORM_LIST_REQUEST: 'PLATFORM_LIST_REQUEST',
    PLATFORM_LIST_SUCCESS: 'PLATFORM_LIST_SUCCESS',
    PLATFORM_LIST_FAIL: 'PLATFORM_LIST_FAIL',
    PLATFORM_DETAILS_REQUEST: 'PLATFORM_DETAILS_REQUEST',
    PLATFORM_DETAILS_SUCCESS: 'PLATFORM_DETAILS_SUCCESS',
    PLATFORM_DETAILS_FAIL: 'PLATFORM_DETAILS_FAIL',
    PLATFORM_CREATE_REQUEST: 'PLATFORM_CREATE_REQUEST',
    PLATFORM_CREATE_SUCCESS: 'PLATFORM_CREATE_SUCCESS',
    PLATFORM_CREATE_FAIL: 'PLATFORM_CREATE_FAIL'
})
